# fly.toml app configuration file generated for rough-moon-1212 on 2023-10-19T07:05:44+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "rough-moon-1212"
primary_region = "sin"
console_command = "/code/manage.py shell"

[build]

[env]
  PORT = "8000"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[statics]]
  guest_path = "/code/static"
  url_prefix = "/static/"
